pipeline{
  agent none
  
  /*
  tools{
    maven '3.6.3'
  }
  */

  stages{
    stage("Build Spring Project"){
      agent { label 'master' } 
      steps{
        //sh "mvn clean package"
          script{
               docker.image('maven:3.6.3'').inside{
                       sh "mvn clean package"
               }
                    
               docker.withRegistry('', 'docker-hub'){
                        //docker login -u xeng -p ****
                        def customImage = docker.build("xeng/register-VV1:1.2.3")
                        customImage.push()
             }
          }
      }
    }
    /*
    stage("Build Docker Image"){
      agent { label 'master' } 
      steps{
        withCredentials([usernamePassword(credentialsId: 'docker-hub', passwordVariable: 'PASSWORD', usernameVariable: 'USERNAME')]) {
            sh "docker login -u ${USERNAME} -p ${PASSWORD}"
            sh "docker build -t xeng/register-g3:1.1 ."
            sh "docker push xeng/register-g3:1.1" 
        }
        sh 'docker logout'
      }
    }
    */
    /*
    stage("Deploy Service"){
      agent { label 'worker5' } 
      steps{
        sh "docker compose up -d --build"
      }
    }
    */
  }
  
  
}
